/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import javax.swing.table.DefaultTableModel;
import modelo.FacadeEquipos;
import modelo.FacadePrestamos;
import modelo.FacadeUsuarios;
import modelo.FacadeViewReporte;
import modelo.entidades.Equipo;
import modelo.entidades.Prestamo;
import modelo.entidades.Usuario;
import modelo.entidades.ViewReportePrestamos;
import Controladores.IniciarDatos;

/**
 *
 * @author mjavi
 */
public class PrestamosITCA extends javax.swing.JFrame {

	/**
	 * Creates new form PrestamosITCA
	 */
	public PrestamosITCA() {
		initComponents();
		iniciarTablas(); //LLAMAR AL METODO QUE VA A INICAR LOS DATOS DE TODAS LAS TABLAS
	}
	
	public void iniciarTablas(){ // INICAR LOD DATOS DE TODAS LAS TABLAS
		IniciarDatos op = new IniciarDatos();//HACER REFERENCIA A LA CLASE DON INICIAMOS LOS DATOS
		
		// INICIAR LA TABLA DE REPORTES CON LOS DATOS DE LA VISTA REPORTE
		op.IniciarDatosReporte((DefaultTableModel) tblReporte.getModel()); 
		
		// INICIAR LA TABLA DE USUARIOS CON LOS DATOS DE LOS USUARIOS
		op.IniciarDatosUsuarios((DefaultTableModel) tblUsuarios.getModel());
		
		// INIICAR LA TABLA DE LOS EQUIPOS CON LOS DATOS DE LOS EQUIPOS
		op.IniciarDatosEqipos((DefaultTableModel) tblEquipos.getModel());
		
		// INICIAR LA TABLA DE LOS PRESTAMOS CON LOS DATOS DE LOS PRESTAMOS
		op.IniciarDatosPrestamos((DefaultTableModel) tblPrestamo.getModel());
	}



	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jTabbedPane1 = new javax.swing.JTabbedPane();
                jPanel1 = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                tblReporte = new javax.swing.JTable();
                jPanel2 = new javax.swing.JPanel();
                jPanel4 = new javax.swing.JPanel();
                jButton3 = new javax.swing.JButton();
                btnEliminarUsuario = new javax.swing.JButton();
                btnGuardarUsuario = new javax.swing.JButton();
                jLabel2 = new javax.swing.JLabel();
                txtIdUsuario = new javax.swing.JTextField();
                txtCedula = new javax.swing.JTextField();
                jLabel5 = new javax.swing.JLabel();
                txtNombres = new javax.swing.JTextField();
                jLabel6 = new javax.swing.JLabel();
                txtApellidos = new javax.swing.JTextField();
                jLabel7 = new javax.swing.JLabel();
                txtDireccion = new javax.swing.JTextField();
                jLabel9 = new javax.swing.JLabel();
                txtEmail = new javax.swing.JTextField();
                jLabel10 = new javax.swing.JLabel();
                txtTelefono = new javax.swing.JTextField();
                jLabel11 = new javax.swing.JLabel();
                btnLimpiarUsuario = new javax.swing.JButton();
                jScrollPane2 = new javax.swing.JScrollPane();
                tblUsuarios = new javax.swing.JTable();
                txtBuscarUsuario = new javax.swing.JTextField();
                btnBuscarUsuario = new javax.swing.JButton();
                jPanel3 = new javax.swing.JPanel();
                jScrollPane3 = new javax.swing.JScrollPane();
                tblEquipos = new javax.swing.JTable();
                jPanel6 = new javax.swing.JPanel();
                jButton6 = new javax.swing.JButton();
                btnEliminarEquipo = new javax.swing.JButton();
                btnGuardarEquipo = new javax.swing.JButton();
                jLabel8 = new javax.swing.JLabel();
                txtIdEquipo = new javax.swing.JTextField();
                txtDescripcion = new javax.swing.JTextField();
                jLabel12 = new javax.swing.JLabel();
                txtMarca = new javax.swing.JTextField();
                jLabel13 = new javax.swing.JLabel();
                txtModelo = new javax.swing.JTextField();
                jLabel14 = new javax.swing.JLabel();
                txtDepartamento = new javax.swing.JTextField();
                jLabel15 = new javax.swing.JLabel();
                txtCantidad = new javax.swing.JTextField();
                jLabel16 = new javax.swing.JLabel();
                txtColor = new javax.swing.JTextField();
                jLabel17 = new javax.swing.JLabel();
                btnLimpiarEquipo = new javax.swing.JButton();
                txtBuscarEquipo = new javax.swing.JTextField();
                btnBuscarEquipo = new javax.swing.JButton();
                jPanel5 = new javax.swing.JPanel();
                jPanel7 = new javax.swing.JPanel();
                jButton7 = new javax.swing.JButton();
                jButton14 = new javax.swing.JButton();
                jButton15 = new javax.swing.JButton();
                jLabel18 = new javax.swing.JLabel();
                txtIdPrestamo = new javax.swing.JTextField();
                txtEquipo = new javax.swing.JTextField();
                jLabel19 = new javax.swing.JLabel();
                txtUsuario = new javax.swing.JTextField();
                jLabel20 = new javax.swing.JLabel();
                txtFechaSalida = new javax.swing.JTextField();
                jLabel21 = new javax.swing.JLabel();
                txtFechaEntrega = new javax.swing.JTextField();
                jLabel24 = new javax.swing.JLabel();
                jButton16 = new javax.swing.JButton();
                txtBuscarPrestamo = new javax.swing.JTextField();
                btnBuscarPrestamo = new javax.swing.JButton();
                jScrollPane4 = new javax.swing.JScrollPane();
                tblPrestamo = new javax.swing.JTable();
                jLabel1 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Préstamos ITCA");

                jTabbedPane1.setBackground(new java.awt.Color(0, 255, 102));
                jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
                jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

                jPanel1.setBackground(new java.awt.Color(255, 255, 255));

                tblReporte.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {

                        },
                        new String [] {
                                "NUM", "Nombre", "Descripcion", "Marca", "Modelo", "Color", "Cantidad", "Departamento", "Fecha salida", "Fecha entrega"
                        }
                ) {
                        Class[] types = new Class [] {
                                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                        };
                        boolean[] canEdit = new boolean [] {
                                false, false, false, false, false, false, false, false, false, false
                        };

                        public Class getColumnClass(int columnIndex) {
                                return types [columnIndex];
                        }

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit [columnIndex];
                        }
                });
                jScrollPane1.setViewportView(tblReporte);
                if (tblReporte.getColumnModel().getColumnCount() > 0) {
                        tblReporte.getColumnModel().getColumn(0).setResizable(false);
                        tblReporte.getColumnModel().getColumn(1).setResizable(false);
                        tblReporte.getColumnModel().getColumn(2).setResizable(false);
                        tblReporte.getColumnModel().getColumn(3).setResizable(false);
                        tblReporte.getColumnModel().getColumn(4).setResizable(false);
                        tblReporte.getColumnModel().getColumn(5).setResizable(false);
                        tblReporte.getColumnModel().getColumn(6).setResizable(false);
                        tblReporte.getColumnModel().getColumn(7).setResizable(false);
                        tblReporte.getColumnModel().getColumn(7).setHeaderValue("Departamento");
                        tblReporte.getColumnModel().getColumn(8).setHeaderValue("Fecha salida");
                        tblReporte.getColumnModel().getColumn(9).setHeaderValue("Fecha entrega");
                }

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
                                .addContainerGap())
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                                .addContainerGap())
                );

                jTabbedPane1.addTab("Reportes", jPanel1);

                jPanel2.setBackground(new java.awt.Color(255, 255, 255));

                jButton3.setText("Editar");

                btnEliminarUsuario.setText("Eliminar");

                btnGuardarUsuario.setText("Guardar");

                jLabel2.setText("ID:");

                txtIdUsuario.setEditable(false);

                jLabel5.setText("Cédula:");

                jLabel6.setText("Nombres:");

                jLabel7.setText("Apellidos:");

                jLabel9.setText("Dirección:");

                jLabel10.setText("E-mail:");

                jLabel11.setText("Teléfono:");

                btnLimpiarUsuario.setText("Limpiar");

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9)
                                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2)
                                        .addComponent(txtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5)
                                        .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6)
                                        .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7)
                                        .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(btnEliminarUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                        .addComponent(btnLimpiarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(btnGuardarUsuario)
                                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jPanel4Layout.setVerticalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnLimpiarUsuario)
                                        .addComponent(btnGuardarUsuario))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton3)
                                        .addComponent(btnEliminarUsuario))
                                .addContainerGap(40, Short.MAX_VALUE))
                );

                tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {

                        },
                        new String [] {
                                "ID", "Cédula", "Nombres", "Apellidos", "Teléfono", "E-mail", "Dirección"
                        }
                ) {
                        Class[] types = new Class [] {
                                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                        };
                        boolean[] canEdit = new boolean [] {
                                false, false, false, false, false, false, false
                        };

                        public Class getColumnClass(int columnIndex) {
                                return types [columnIndex];
                        }

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit [columnIndex];
                        }
                });
                tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                tblUsuariosMouseClicked(evt);
                        }
                });
                jScrollPane2.setViewportView(tblUsuarios);
                if (tblUsuarios.getColumnModel().getColumnCount() > 0) {
                        tblUsuarios.getColumnModel().getColumn(0).setResizable(false);
                        tblUsuarios.getColumnModel().getColumn(1).setResizable(false);
                        tblUsuarios.getColumnModel().getColumn(2).setResizable(false);
                        tblUsuarios.getColumnModel().getColumn(3).setResizable(false);
                        tblUsuarios.getColumnModel().getColumn(4).setResizable(false);
                        tblUsuarios.getColumnModel().getColumn(5).setResizable(false);
                        tblUsuarios.getColumnModel().getColumn(6).setResizable(false);
                }

                btnBuscarUsuario.setText("Buscar");

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(txtBuscarUsuario)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnBuscarUsuario))
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE))
                                .addContainerGap())
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnBuscarUsuario))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );

                jTabbedPane1.addTab("Usuarios", jPanel2);

                jPanel3.setBackground(new java.awt.Color(255, 255, 255));

                tblEquipos.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {

                        },
                        new String [] {
                                "ID", "Descripción", "Marca", "Modelo", "Color", "Cantidad", "Departamento"
                        }
                ) {
                        Class[] types = new Class [] {
                                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                        };
                        boolean[] canEdit = new boolean [] {
                                false, false, false, false, false, false, false
                        };

                        public Class getColumnClass(int columnIndex) {
                                return types [columnIndex];
                        }

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit [columnIndex];
                        }
                });
                tblEquipos.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                tblEquiposMouseClicked(evt);
                        }
                });
                jScrollPane3.setViewportView(tblEquipos);
                if (tblEquipos.getColumnModel().getColumnCount() > 0) {
                        tblEquipos.getColumnModel().getColumn(0).setResizable(false);
                        tblEquipos.getColumnModel().getColumn(1).setResizable(false);
                        tblEquipos.getColumnModel().getColumn(2).setResizable(false);
                        tblEquipos.getColumnModel().getColumn(3).setResizable(false);
                        tblEquipos.getColumnModel().getColumn(4).setResizable(false);
                        tblEquipos.getColumnModel().getColumn(5).setResizable(false);
                        tblEquipos.getColumnModel().getColumn(6).setResizable(false);
                }

                jButton6.setText("Editar");

                btnEliminarEquipo.setText("Eliminar");

                btnGuardarEquipo.setText("Guardar");

                jLabel8.setText("ID:");

                txtIdEquipo.setEditable(false);

                jLabel12.setText("Descripción:");

                jLabel13.setText("Marca:");

                jLabel14.setText("Modelo");

                jLabel15.setText("Departamento:");

                jLabel16.setText("Cantidad:");

                jLabel17.setText("Color:");

                btnLimpiarEquipo.setText("Limpiar");

                javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
                jPanel6.setLayout(jPanel6Layout);
                jPanel6Layout.setHorizontalGroup(
                        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel17)
                                        .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel16)
                                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel15)
                                        .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8)
                                        .addComponent(txtIdEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12)
                                        .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel13)
                                        .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel14)
                                        .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(btnEliminarEquipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                        .addComponent(btnLimpiarEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(btnGuardarEquipo)
                                                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jPanel6Layout.setVerticalGroup(
                        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnLimpiarEquipo)
                                        .addComponent(btnGuardarEquipo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton6)
                                        .addComponent(btnEliminarEquipo))
                                .addContainerGap(40, Short.MAX_VALUE))
                );

                btnBuscarEquipo.setText("Buscar");

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(txtBuscarEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnBuscarEquipo))
                                        .addComponent(jScrollPane3))
                                .addContainerGap())
                );
                jPanel3Layout.setVerticalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtBuscarEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnBuscarEquipo))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );

                jTabbedPane1.addTab("Equipos", jPanel3);

                jPanel5.setBackground(new java.awt.Color(255, 255, 255));

                jButton7.setText("Editar");

                jButton14.setText("Eliminar");

                jButton15.setText("Guardar");

                jLabel18.setText("ID:");

                txtIdPrestamo.setEditable(false);

                jLabel19.setText("Equipo:");

                jLabel20.setText("Usuario:");

                jLabel21.setText("Fecha salida:");

                jLabel24.setText("Fecha entrega:");

                jButton16.setText("Limpiar");

                javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
                jPanel7.setLayout(jPanel7Layout);
                jPanel7Layout.setHorizontalGroup(
                        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel24)
                                        .addComponent(txtFechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel18)
                                        .addComponent(txtIdPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel19)
                                        .addComponent(txtEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel20)
                                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel21)
                                        .addComponent(txtFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jButton14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                        .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jButton15)
                                                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jPanel7Layout.setVerticalGroup(
                        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton16)
                                        .addComponent(jButton15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton7)
                                        .addComponent(jButton14))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                btnBuscarPrestamo.setText("Buscar");

                tblPrestamo.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {

                        },
                        new String [] {
                                "ID", "Equipo", "Usuario", "Fecha salida", "Fecha entrega"
                        }
                ) {
                        Class[] types = new Class [] {
                                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                        };
                        boolean[] canEdit = new boolean [] {
                                false, false, false, false, false
                        };

                        public Class getColumnClass(int columnIndex) {
                                return types [columnIndex];
                        }

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit [columnIndex];
                        }
                });
                tblPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                tblPrestamoMouseClicked(evt);
                        }
                });
                jScrollPane4.setViewportView(tblPrestamo);
                if (tblPrestamo.getColumnModel().getColumnCount() > 0) {
                        tblPrestamo.getColumnModel().getColumn(0).setResizable(false);
                        tblPrestamo.getColumnModel().getColumn(1).setResizable(false);
                        tblPrestamo.getColumnModel().getColumn(2).setResizable(false);
                        tblPrestamo.getColumnModel().getColumn(3).setResizable(false);
                        tblPrestamo.getColumnModel().getColumn(4).setResizable(false);
                }

                javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                jPanel5.setLayout(jPanel5Layout);
                jPanel5Layout.setHorizontalGroup(
                        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(txtBuscarPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnBuscarPrestamo))
                                        .addComponent(jScrollPane4))
                                .addContainerGap())
                );
                jPanel5Layout.setVerticalGroup(
                        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtBuscarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnBuscarPrestamo))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 133, Short.MAX_VALUE)))
                                .addContainerGap())
                );

                jTabbedPane1.addTab("Préstamos", jPanel5);

                jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jLabel1.setText("CONTROL DE PRESTAMOS DE EQUIPOS MULTIMEDIA DEL");

                jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jLabel3.setText("NSTITUTO TECNOLÓGICO SUPERIOR \"JOSÉ CHIRIBOGA GRIJALVA\"");

                jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/escudo.jpeg"))); // NOI18N
                jLabel4.setToolTipText("");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel1))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel4))
                                        .addComponent(jTabbedPane1))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel3))
                                        .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTabbedPane1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
                // TODO add your handling code here:
		//OBTENER EL VALOR DE LA CELDA "ID" DE LA FILA SELECCIONADA DE LA TABLA USUARIOS
		int id = Integer.parseInt(String.valueOf(tblUsuarios.getValueAt(tblUsuarios.getSelectedRow(), 0)));
		//OBTENER EL UN USUARIO EN BASE A NUESTRO ID
		Usuario usuario = FacadeUsuarios.getUsuario(id);
		//LLENAR LOS TEXTBOX CON LOS VALORES DE NUESTRO USUARIO
		txtIdUsuario.setText(String.valueOf(usuario.getIdUsuario()));
		txtCedula.setText(usuario.getCedula());
		txtNombres.setText(usuario.getNombres());
		txtApellidos.setText(usuario.getApellidos());
		txtTelefono.setText(usuario.getTelefono());
		txtEmail.setText(usuario.getEmail());
		txtDireccion.setText(usuario.getDireccion());
		//int IdUsuario = Integer.parseInt(dtm.getValueAt(tblUsuarios.getSelectedRow(), 0));
        }//GEN-LAST:event_tblUsuariosMouseClicked

        private void tblEquiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEquiposMouseClicked
                // TODO add your handling code here:
		//OBTENER EL VALOR DE LA CELDA "ID" DE LA FILA SELLECCIONADA DE LA TABLA EQUIPOS
		int id = Integer.parseInt(String.valueOf(tblEquipos.getValueAt(tblEquipos.getSelectedRow(), 0)));
		//OBTENER UN EQUIPO EN BASE A NUESTRO ID
		Equipo equipo = FacadeEquipos.getEquipo(id);
		//LLENAR LOS TEXTBOX CON LOS VALORES DE NUESTRO EQUIPO
		txtIdEquipo.setText(String.valueOf(equipo.getIdEquipo()));
		txtDescripcion.setText(equipo.getDescripcion());
		txtMarca.setText(equipo.getMarca());
		txtModelo.setText(equipo.getModelo());
		txtColor.setText(equipo.getColor());
		txtCantidad.setText(String.valueOf(equipo.getCantidad()));
		txtDepartamento.setText(equipo.getPropiedad());
		
        }//GEN-LAST:event_tblEquiposMouseClicked

        private void tblPrestamoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPrestamoMouseClicked
                // TODO add your handling code here:
		//OBTENER EL VALOR DE LA CELDA "ID" DE LA FILA SELECCIONADA DE LA TABLA PRESTAMOS
		int id = Integer.parseInt(String.valueOf(tblPrestamo.getValueAt(tblPrestamo.getSelectedRow(), 0)));
		//OBTENER UN PRESTAMO EN BASE A NUESTRO ID
		Prestamo prestamo = FacadePrestamos.getPrestamo(id);
		//
		//LLENAR LOS TEXTOX CON LOS VALORES DE NUESTRO PRESTAMO
		
        }//GEN-LAST:event_tblPrestamoMouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(PrestamosITCA.class
				.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(PrestamosITCA.class
				.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(PrestamosITCA.class
				.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(PrestamosITCA.class
				.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new PrestamosITCA().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnBuscarEquipo;
        private javax.swing.JButton btnBuscarPrestamo;
        private javax.swing.JButton btnBuscarUsuario;
        private javax.swing.JButton btnEliminarEquipo;
        private javax.swing.JButton btnEliminarUsuario;
        private javax.swing.JButton btnGuardarEquipo;
        private javax.swing.JButton btnGuardarUsuario;
        private javax.swing.JButton btnLimpiarEquipo;
        private javax.swing.JButton btnLimpiarUsuario;
        private javax.swing.JButton jButton14;
        private javax.swing.JButton jButton15;
        private javax.swing.JButton jButton16;
        private javax.swing.JButton jButton3;
        private javax.swing.JButton jButton6;
        private javax.swing.JButton jButton7;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel13;
        private javax.swing.JLabel jLabel14;
        private javax.swing.JLabel jLabel15;
        private javax.swing.JLabel jLabel16;
        private javax.swing.JLabel jLabel17;
        private javax.swing.JLabel jLabel18;
        private javax.swing.JLabel jLabel19;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel20;
        private javax.swing.JLabel jLabel21;
        private javax.swing.JLabel jLabel24;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JPanel jPanel5;
        private javax.swing.JPanel jPanel6;
        private javax.swing.JPanel jPanel7;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JScrollPane jScrollPane3;
        private javax.swing.JScrollPane jScrollPane4;
        private javax.swing.JTabbedPane jTabbedPane1;
        private javax.swing.JTable tblEquipos;
        private javax.swing.JTable tblPrestamo;
        private javax.swing.JTable tblReporte;
        private javax.swing.JTable tblUsuarios;
        private javax.swing.JTextField txtApellidos;
        private javax.swing.JTextField txtBuscarEquipo;
        private javax.swing.JTextField txtBuscarPrestamo;
        private javax.swing.JTextField txtBuscarUsuario;
        private javax.swing.JTextField txtCantidad;
        private javax.swing.JTextField txtCedula;
        private javax.swing.JTextField txtColor;
        private javax.swing.JTextField txtDepartamento;
        private javax.swing.JTextField txtDescripcion;
        private javax.swing.JTextField txtDireccion;
        private javax.swing.JTextField txtEmail;
        private javax.swing.JTextField txtEquipo;
        private javax.swing.JTextField txtFechaEntrega;
        private javax.swing.JTextField txtFechaSalida;
        private javax.swing.JTextField txtIdEquipo;
        private javax.swing.JTextField txtIdPrestamo;
        private javax.swing.JTextField txtIdUsuario;
        private javax.swing.JTextField txtMarca;
        private javax.swing.JTextField txtModelo;
        private javax.swing.JTextField txtNombres;
        private javax.swing.JTextField txtTelefono;
        private javax.swing.JTextField txtUsuario;
        // End of variables declaration//GEN-END:variables

//public void IniciarDatosUsuarios() {
//		FacadeUsuarios fac = new FacadeUsuarios();
//		DefaultTableModel dtm = (DefaultTableModel) tblUsuarios.getModel();
//		dtm.setRowCount(0);
//		FacadeUsuarios.getListUsuario()
//			.stream()
//			.map(
//				(item) -> new Object[]{item.getCedula(), item.getNombres(), item.getApellidos(),
//					item.getTelefono(), item.getEmail(), item.getDireccion()}
//			).forEach(
//				(fila) -> {
//					dtm.addRow(fila);
//				}
//			);
//	}

}
