/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import Controladores.AceptarDatos;
import Controladores.IniciarDatos;
import javax.swing.table.DefaultTableModel;
import modelo.FacadeEquipos;
import modelo.FacadeUsuarios;
import modelo.entidades.Equipo;
import modelo.entidades.Usuario;

/**
 *
 * @author mjavi
 */
public class RegistroEquipos extends javax.swing.JDialog {

	/**
	 * Creates new form NewJDialog
	 */
	public RegistroEquipos(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		iniciarDatos();
	}

	PrestamosITCA parentFrame;

	public RegistroEquipos(PrestamosITCA parentFrame) {
		this.parentFrame = parentFrame;
		initComponents();
		iniciarDatos();
	}

	Equipo equipo;
	
	public void iniciarDatos(){
		//LLENAR LA TABLA CON LOS DATOS DE LO USUARIOS
		IniciarDatos iniciar = new IniciarDatos();
		iniciar.IniciarDatosEqipos((DefaultTableModel)tblEquipos.getModel());
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                jScrollPane3 = new javax.swing.JScrollPane();
                tblEquipos = new javax.swing.JTable();
                btnAceptarEquipo = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

                jLabel1.setText("SELECCIONAR EQUIPOS");

                tblEquipos.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {

                        },
                        new String [] {
                                "ID", "Descripción", "Marca", "Modelo", "Color", "Cantidad", "Departamento"
                        }
                ) {
                        Class[] types = new Class [] {
                                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                        };
                        boolean[] canEdit = new boolean [] {
                                false, false, false, false, false, false, false
                        };

                        public Class getColumnClass(int columnIndex) {
                                return types [columnIndex];
                        }

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit [columnIndex];
                        }
                });
                tblEquipos.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                tblEquiposMouseClicked(evt);
                        }
                });
                jScrollPane3.setViewportView(tblEquipos);

                btnAceptarEquipo.setText("Aceptar");
                btnAceptarEquipo.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAceptarEquipoActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 863, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnAceptarEquipo)))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAceptarEquipo)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void tblEquiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEquiposMouseClicked
		// TODO add your handling code here:
		//OBTENER EL VALOR DE LA CELDA "ID" DE LA FILA SELLECCIONADA DE LA TABLA EQUIPOS
		int id = Integer.parseInt(String.valueOf(tblEquipos.getValueAt(tblEquipos.getSelectedRow(), 0)));
		//OBTENER UN EQUIPO EN BASE A NUESTRO ID
		equipo = FacadeEquipos.getEquipo(id);
        }//GEN-LAST:event_tblEquiposMouseClicked

        private void btnAceptarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarEquipoActionPerformed
		// TODO add your handling code here:
		//ENVIAR EL EQUIPO A LA CLASE ACEPTAR DATOS PARA QUE SEA USADO POR LA CLASE PRESTAMOS ITCA
		//HACER REFERENCIA A LA CLASE ACEPTAR DATOS
		AceptarDatos aceptar = new AceptarDatos(equipo);
		aceptar.registrarEquipo();
		parentFrame.txtEquipo.setText(equipo.getDescripcion());
		//CERRAR ESTA VENTANA
		this.dispose();
        }//GEN-LAST:event_btnAceptarEquipoActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(RegistroEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(RegistroEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(RegistroEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(RegistroEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				RegistroEquipos dialog = new RegistroEquipos(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnAceptarEquipo;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JScrollPane jScrollPane3;
        private javax.swing.JTable tblEquipos;
        // End of variables declaration//GEN-END:variables
}
